### PR TITLE
Removed trailing space?

### PR DESCRIPTION
**Pull request by PixelDud**
This change should remove the trailing space behind the "?" in polls, as per Lucinotion's request.

### CODE REVIEW

**Comment by pennro-se** [comment]
Shouldn't leave empty strings in there. They are unnecessary.
As well, I think you are affecting more than just the space after the `?` here. Make sure to test your changes.

**Comment by PixelDud** [comment]
I think that I'm going to learn a bit more JavaScript before messing with this and run tests before making commits.

**Comment by PixelDud** [comment]
Was unable to test the changes due to an error setting it up, will leave development to y'all for now.

**Comment by pennro-se** [comment]
What issues did you have when setting it up? It would be good to know so we can correct the instructions if needed.

You could also test the logic of this module separately since the issue being corrected by this PR isn't related to the Discord.js library.

If you wish, contact Skeddles on discord for access to the Lospec Bot development channel so further discussions can take place.

**Comment by PixelDud** [comment]
I was trying to run the modified bot on my server, though it kept giving errors about not having the sentience and image only channels setup. I attempted to direct it to some specified channels, though the errors persisted.

**Pull request closed without merging**
